#!/usr/bin/env php
<?php
$fileName = array_shift($argv);

foreach ($argv as $arg) {
    switch ($arg) {
        case 'serve':
            exec('symfony server:start --port=8000 --passthru=front.php');
            break;
        default:
            exit('No valid commands');
            break;
    }

}
