#!/usr/bin/env php
<?php
require 'vendor/autoload.php';

use Roi\Route;

$fileName = array_shift($argv);
if(empty($argv)) {
    $argv = ['default'];
}

foreach ($argv as $arg) {
    switch ($arg) {
        case 'serve':
            exec('symfony server:start --port=8000 --passthru=front.php');
            break;
        case 'routes':
            $route = new Route();
            include __DIR__ . '/App/Config/routes.php';
            $routes = $route->getRoutes();
            dd($routes);
            break;
        case 'quote':
        default:
            $quotes = [
                'When there is no desire, all things are at peace. - Laozi',
                'Simplicity is the ultimate sophistication. - Leonardo da Vinci',
                'Simplicity is the essence of happiness. - Cedric Bledsoe',
                'Smile, breathe, and go slowly. - Thich Nhat Hanh',
                'Simplicity is an acquired taste. - Katharine Gerould',
                'Well begun is half done. - Aristotle',
                'He who is contented is rich. - Laozi',
                'Very little is needed to make a happy life. - Marcus Antoninus',
                'It is quality rather than quantity that matters. - Lucius Annaeus Seneca',
                'Genius is one percent inspiration and ninety-nine percent perspiration. - Thomas Edison',
                'Computer science is no more about computers than astronomy is about telescopes. - Edsger Dijkstra',
                'It always seems impossible until it is done. - Nelson Mandela',
                'Act only according to that maxim whereby you can, at the same time, will that it should become a universal law. - Immanuel Kant',
            ];
            $quote = array_rand($quotes, 1);

            if ($arg === 'quote') {
                echo PHP_EOL . $quotes[$quote] . PHP_EOL;
            } else {
                echo 'No valid commands, but here is a quote:' . PHP_EOL.PHP_EOL . $quotes[$quote] . PHP_EOL;
            }

            exit(1);
            break;
    }

}
